name: "12-Management-CD"
on:
  push:
    #types:
    #  - opened
    #  - reopened
    #  - synchronize
    branches:
      - main
    paths:
      - "12-management/**"
  workflow_dispatch:
    inputs:
      terraform_action:
        description: "Terraform Action to Perform"
        required: true
        default: "apply"
        type: choice
        options:
          - "apply"
          - "destroy"

jobs:
  validate_and_plan:
    name: "12-CD"
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    uses: Enterprise-Scale-Piotr/core-platform-caf-alz-public/.github/workflows/template-cd.yaml@main
    with:
      gh_workflow: 12-management
    secrets: inherit
