name: '12-Management-CI'
on:
  pull_request:
    #types:
    #  - opened
    #  - reopened
    #  - synchronize
    branches:
      - main
    paths:
      - "management/**"
  workflow_dispatch:

jobs:
  validate_and_plan:
    name: "CI"
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    uses: Enterprise-Scale-Piotr/core-platform-caf-alz-public/.github/workflows/template-ci.yaml@main
    with:
      gh_workflow: management
    secrets: inherit
